"""change type of the tags column

Revision ID: 8c86e705f20e
Revises: 2d82b92502d4
Create Date: 2025-02-15 11:15:05.125613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8c86e705f20e'
down_revision = '2d82b92502d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.String(length=250),
               type_=sqlite.JSON(),
               existing_nullable=False)

    # ### end Alembic commands ###
